name: new-jobs

on: [push]

jobs:
 
  job1:
  
    runs-on: ubuntu-latest

    steps: 

    - run: ls -a
    - name: Checkout
      uses: actions/checkout@v2.5.0 # Default repo to clone down / checkout is our one
    - run: echo '${{github.repository}}'
    - run: ls -a
       